spring:
  application:
    name: spring-cloud-websocket-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 35
server:
  port: 8801

logging:
  level:
    root: info
  file: ../logs/${spring.application.name}.log